# docker build -f Dockerfile.tf_x86 -t byodr/tf .
FROM tensorflow/tensorflow:1.9.0-gpu

ENV TZ=Europe/Amsterdam
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y --no-install-recommends \
    python-opencv \
    python-pip \
    python-setuptools \
 && rm -rf /var/lib/apt/lists/*

RUN pip install "pyzmq >=18.1, <19.0"