# docker build -f Dockerfile.bionic -t byodr/bionic:1.0 .
FROM ubuntu:bionic

ENV TZ=Europe/Amsterdam
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python-dev \
    python-opencv \
    python-pip \
    python-setuptools \
    python-wheel \
 && rm -rf /var/lib/apt/lists/*

RUN pip install "pyzmq >=18.1, <19.0"