FROM byodr/ros_melodic

COPY . app/
WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt

RUN groupadd --gid 1000 --system app \
  && useradd --uid 1000 --gid 1000 --system --create-home --shell /bin/bash app

#  PYTHONPATH=.:/usr/lib/python2.7/dist-packages:${PYTHONPATH}

ENTRYPOINT ["/ros_entrypoint.sh"]