FROM centipede2donald/ros-melodic:rosserial

COPY ./vehicles/rover/*.launch app/
WORKDIR /app

# Use the plugdev group.
RUN useradd --uid 1990 --gid 46 --system --create-home --shell /bin/bash byodr

USER byodr

ENTRYPOINT ["/ros_entrypoint.sh"]

CMD ["roslaunch", "rosserial.launch"]